// Sound-effects library manifest (bundled CC0 pack) + instance helpers.
import { newId } from "./projectStore";

// Bundled sounds live in public/sfx/ (generated by scripts/gen-sfx.mjs).
export const SFX_LIBRARY = [
  { id: "whoosh", label: "Whoosh", file: "/sfx/whoosh.wav" },
  { id: "swoosh", label: "Swoosh", file: "/sfx/swoosh.wav" },
  { id: "pop", label: "Pop", file: "/sfx/pop.wav" },
  { id: "ding", label: "Ding", file: "/sfx/ding.wav" },
  { id: "click", label: "Click", file: "/sfx/click.wav" },
  { id: "boom", label: "Boom", file: "/sfx/boom.wav" },
];

// A placed SFX instance on the timeline.
//   src: { kind:"lib", file } (bundled) | { kind:"upload", mediaId } (project media)
export function makeSfx(name, src, at, volume = 0.8) {
  return { id: newId(), name, src, at: Math.max(0, +at || 0), volume };
}

// Strip the runtime-only `url` before persisting.
export function serializeSfx(list) {
  return (list || []).map(({ id, name, src, at, volume }) => ({ id, name, src, at, volume }));
}
